#!/usr/bin/env python3
"""Render the share image (og:image / twitter:image) for EVERY public page and
write the matching head tags. One data table drives it: tools/og/pages.json.

    python3 tools/og/gen_og.py              render all images + rewrite head tags
    python3 tools/og/gen_og.py --tags-only  rewrite head tags only (after a build bump)
    python3 tools/og/gen_og.py --only features/gex.html,about.html
    python3 tools/og/gen_og.py --sheet out.png   also write a contact sheet

Card layout (same look as the first /features share cards): dark brand
background with a soft mint glow, the page's descriptive title top-left with a
mint underline, the Stryker dragon emblem top-right, and a real capture of the
page (or the logo wordmark for brand-only pages) in a rounded frame below.
The bottom-left corner of the frame is kept free of anything important because
X draws the og:title over it.

Images go to assets/images/og/share/<page with / as _>.png (JPEG when the PNG
would be over 300 KB). Head tags use absolute https URLs with ?v=<build> so
chat apps fetch the new image for new shares. Learn pages are generated by
tools/gen-learn.js, which reads the same table and emits the same tags.

Text rule: titles are page names only. No results, win rates, profits, prices
or timing words on any card. Pillow is the only dependency; no network.
"""
import argparse
import html as htmlmod
import io
import json
import os
import re
import sys

from PIL import Image, ImageDraw, ImageFilter, ImageFont

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
TABLE = os.path.join(ROOT, 'tools', 'og', 'pages.json')
OUT_REL = 'assets/images/og/share'
SITE = 'https://strykertrading.com/'
W, H = 1200, 630
BG = (10, 10, 12)
FRAME = (44, 44, 50)
TEXT = (245, 245, 247)
ACCENT = (3, 201, 136)
MAX_BYTES = 300 * 1024
PAD = 40
BAND = 132
FONT_SIZE = 80


def load_table():
    with open(TABLE, encoding='utf-8') as fh:
        return json.load(fh)['pages']


def image_stem(page):
    return page[:-5].replace('/', '_')


def font(size, mono=False):
    name = 'jetbrains-mono-latin-variable.woff2' if mono else 'archivo-latin-variable.woff2'
    var = b'Medium' if mono else b'ExtraBold'
    for path, v in ((os.path.join(ROOT, 'assets', 'fonts', name), var),
                    ('/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf', None)):
        try:
            f = ImageFont.truetype(path, size)
            if v:
                try:
                    f.set_variation_by_name(v)
                except Exception:
                    pass
            return f
        except Exception:
            continue
    sys.exit('No usable font found (Archivo woff2 or DejaVu Sans Bold).')


def cover(im, w, h, fx=0.5, fy=0.0):
    s = max(w / im.width, h / im.height)
    im = im.resize((max(w, round(im.width * s)), max(h, round(im.height * s))), Image.LANCZOS)
    x = round((im.width - w) * fx)
    y = round((im.height - h) * fy)
    return im.crop((x, y, x + w, y + h))


def contain(im, w, h, bg):
    """Fit the whole capture (diagrams must not be cropped), centred on bg."""
    s = min(w / im.width, h / im.height)
    im = im.resize((round(im.width * s), round(im.height * s)), Image.LANCZOS)
    out = Image.new('RGB', (w, h), bg)
    out.paste(im, ((w - im.width) // 2, (h - im.height) // 2))
    return out


def framed(card, im, box, radius=18):
    x0, y0, x1, y1 = box
    w, h = x1 - x0, y1 - y0
    mask = Image.new('L', (w, h), 0)
    ImageDraw.Draw(mask).rounded_rectangle((0, 0, w - 1, h - 1), radius=radius, fill=255)
    shadow = Image.new('RGBA', (W, H), (0, 0, 0, 0))
    ImageDraw.Draw(shadow).rounded_rectangle((x0, y0 + 8, x1, y1 + 8), radius=radius, fill=(0, 0, 0, 170))
    card.alpha_composite(shadow.filter(ImageFilter.GaussianBlur(14)))
    card.paste(im, (x0, y0), mask)
    ImageDraw.Draw(card).rounded_rectangle((x0, y0, x1 - 1, y1 - 1), radius=radius, outline=FRAME, width=2)


def base(title):
    card = Image.new('RGBA', (W, H), BG + (255,))
    glow = Image.new('RGBA', (W, H), (0, 0, 0, 0))
    ImageDraw.Draw(glow).ellipse((-200, -260, 700, 260), fill=ACCENT + (40,))
    card.alpha_composite(glow.filter(ImageFilter.GaussianBlur(90)))
    d = ImageDraw.Draw(card)
    logo = Image.open(os.path.join(ROOT, 'assets', 'images', 'logo-emblem.png')).convert('RGBA')
    ls = 88
    logo = logo.resize((ls, ls), Image.LANCZOS)
    max_w = W - 2 * PAD - ls - 30
    size = FONT_SIZE
    f = font(size)
    while d.textlength(title, font=f) > max_w and size > 52:
        size -= 2
        f = font(size)
    if d.textlength(title, font=f) > max_w:
        sys.exit(f'Title too long for the card: {title!r}')
    # Fixed baseline from the cap height, so every card's title sits the same.
    cap = d.textbbox((0, 0), 'H', font=f)
    ty = (BAND + 6 - (cap[3] - cap[1])) // 2 - cap[1] - 6
    d.text((PAD, ty), title, font=f, fill=TEXT)
    uy = ty + cap[3] + 14
    d.rounded_rectangle((PAD, uy, PAD + 72, uy + 6), radius=3, fill=ACCENT)
    card.alpha_composite(logo, (W - PAD - ls, (BAND + 10 - ls) // 2))
    return card


def visual_box():
    return (PAD, BAND + 6, W - PAD, H - PAD + 10)


def render(entry):
    card = base(entry['title'])
    box = visual_box()
    bw, bh = box[2] - box[0], box[3] - box[1]
    vis = entry['visual']
    if vis == 'brand':
        panel = Image.new('RGB', (bw, bh), (14, 15, 18))
        pd = ImageDraw.Draw(panel)
        for x in range(0, bw, 48):
            pd.line((x, 0, x, bh), fill=(22, 24, 28))
        for y in range(0, bh, 48):
            pd.line((0, y, bw, y), fill=(22, 24, 28))
        g = Image.new('RGBA', (bw, bh), (0, 0, 0, 0))
        ImageDraw.Draw(g).ellipse((bw // 2 - 360, bh // 2 - 170, bw // 2 + 360, bh // 2 + 170), fill=ACCENT + (34,))
        panel = panel.convert('RGBA')
        panel.alpha_composite(g.filter(ImageFilter.GaussianBlur(70)))
        mark = Image.open(os.path.join(ROOT, 'assets', 'images', 'logo-full.png')).convert('RGBA')
        mh = 250
        mark = mark.resize((round(mark.width * mh / mark.height), mh), Image.LANCZOS)
        panel.alpha_composite(mark, ((bw - mark.width) // 2, (bh - mh) // 2 - 22))
        pd = ImageDraw.Draw(panel)
        url = 'strykertrading.com/' + ('' if entry['page'] == 'index.html' else entry['page'][:-5])
        fm = font(26, mono=True)
        tw = pd.textlength(url, font=fm)
        pd.text(((bw - tw) // 2, (bh + mh) // 2 + 2), url, font=fm, fill=(150, 152, 160))
        framed(card, panel.convert('RGB'), box)
    elif len(vis) == 4:
        gap = 16
        x0, y0, x1, y1 = box
        cw = (x1 - x0 - gap) // 2
        ch = (y1 - y0 - gap) // 2
        for i, hp in enumerate(vis):
            cx = x0 + (i % 2) * (cw + gap)
            cy = y0 + (i // 2) * (ch + gap)
            src = Image.open(os.path.join(ROOT, hp)).convert('RGB')
            im = contain(src, cw, ch, (17, 17, 20)) if 'captures/learn-' in hp else cover(src, cw, ch, 0.5, 0.0)
            framed(card, im, (cx, cy, cx + cw, cy + ch), radius=14)
    else:
        src = Image.open(os.path.join(ROOT, vis[0])).convert('RGB')
        if entry.get('crop'):
            # Keep only part of the capture first (fractions), e.g. to leave out demo numbers.
            c = [float(v) for v in entry['crop'].split(',')]
            src = src.crop((round(c[0] * src.width), round(c[1] * src.height), round(c[2] * src.width), round(c[3] * src.height)))
        fx, fy = (float(v) for v in entry.get('focus', '0.5,0.0').split(','))
        if 'captures/learn-' in vis[0]:
            # Diagrams: show them whole on the diagram's own background colour.
            bgc = src.getpixel((4, src.height - 4))
            im = contain(src.crop((2, 2, src.width - 2, src.height - 2)), bw - 40, bh - 24, bgc)
            pad = Image.new('RGB', (bw, bh), bgc)
            pad.paste(im, (20, 12))
            im = pad
        else:
            im = cover(src, bw, bh, fx, fy)
        framed(card, im, box)
    return card


def save(card, stem):
    out_dir = os.path.join(ROOT, OUT_REL)
    os.makedirs(out_dir, exist_ok=True)
    rgb = card.convert('RGB')
    buf = io.BytesIO()
    rgb.save(buf, 'PNG', optimize=True)
    if buf.tell() <= MAX_BYTES:
        ext, data = 'png', buf.getvalue()
    else:
        for q in (90, 86, 82, 78, 74):
            buf = io.BytesIO()
            rgb.save(buf, 'JPEG', quality=q, optimize=True, progressive=True)
            if buf.tell() <= MAX_BYTES:
                break
        ext, data = 'jpg', buf.getvalue()
    for old in ('png', 'jpg'):
        p = os.path.join(out_dir, stem + '.' + old)
        if old != ext and os.path.exists(p):
            os.remove(p)
    with open(os.path.join(out_dir, stem + '.' + ext), 'wb') as fh:
        fh.write(data)
    return f'{OUT_REL}/{stem}.{ext}', len(data)


def image_rel(entry):
    stem = image_stem(entry['page'])
    for ext in ('png', 'jpg'):
        rel = f'{OUT_REL}/{stem}.{ext}'
        if os.path.exists(os.path.join(ROOT, rel)):
            return rel
    return None


def build():
    with open(os.path.join(ROOT, 'assets', 'version.json'), encoding='utf-8') as fh:
        return json.load(fh)['build']


TAG_ORDER = ['og:title', 'og:image', 'og:image:width', 'og:image:height', 'og:image:type', 'og:image:alt',
             'twitter:card', 'twitter:title', 'twitter:image', 'twitter:image:alt']


def tag_values(entry, og_title, rel, ver):
    url = f'{SITE}{rel}?v={ver}'
    return {
        'og:title': og_title, 'og:image': url, 'og:image:width': '1200', 'og:image:height': '630',
        'og:image:type': 'image/png' if rel.endswith('.png') else 'image/jpeg',
        'og:image:alt': entry['alt'], 'twitter:card': 'summary_large_image',
        'twitter:title': og_title, 'twitter:image': url, 'twitter:image:alt': entry['alt'],
    }


def tag_line(key, val):
    attr = 'property' if key.startswith('og:') else 'name'
    return f'<meta {attr}="{key}" content="{htmlmod.escape(val, quote=True)}">'


def tag_re(key):
    attr = 'property' if key.startswith('og:') else 'name'
    return re.compile(r'<meta ' + attr + r'="' + re.escape(key) + r'" content="[^"]*">')


def write_tags(entry, ver):
    """Set the ten share tags in place; a missing tag goes right after the one before it."""
    path = os.path.join(ROOT, entry['page'])
    with open(path, encoding='utf-8') as fh:
        src = fh.read()
    rel = image_rel(entry)
    if not rel:
        sys.exit(f'{entry["page"]}: no image rendered yet')
    if entry.get('og_title'):
        og_title = entry['og_title']
    else:
        m = re.search(r'<meta property="og:title" content="([^"]*)">', src)
        og_title = htmlmod.unescape(m.group(1)) if m else entry['title']
    if entry['title'].lower() not in og_title.lower():
        sys.exit(f'{entry["page"]}: og:title {og_title!r} does not contain the card title {entry["title"]!r}')
    vals = tag_values(entry, og_title, rel, ver)
    new = src
    prev = None
    for key in TAG_ORDER:
        line = tag_line(key, vals[key])
        rx = tag_re(key)
        if rx.search(new):
            new = rx.sub(lambda _m: line, new, count=1)
        else:
            anchor = tag_re(prev).search(new) if prev else None
            if not anchor:
                anchor = re.search(r'<meta property="og:site_name"[^>]*>', new)
            if not anchor:
                sys.exit(f'{entry["page"]}: nowhere to put {key}')
            new = new[:anchor.end()] + '\n' + line + new[anchor.end():]
        prev = key
    # JSON-LD image follows the share image.
    new = new.replace('"https://strykertrading.com/assets/images/og-image.png"', f'"{vals["og:image"]}"')
    if new != src:
        with open(path, 'w', encoding='utf-8') as fh:
            fh.write(new)
        return True
    return False


def sheet(entries, out):
    cols, tw, th, lab = 4, 300, 158, 22
    rows = (len(entries) + cols - 1) // cols
    sh = Image.new('RGB', (cols * (tw + 12) + 12, rows * (th + lab + 12) + 12), (32, 32, 36))
    d = ImageDraw.Draw(sh)
    f = font(13, mono=True)
    for i, e in enumerate(entries):
        im = Image.open(os.path.join(ROOT, image_rel(e))).convert('RGB').resize((tw, th), Image.LANCZOS)
        x = 12 + (i % cols) * (tw + 12)
        y = 12 + (i // cols) * (th + lab + 12)
        sh.paste(im, (x, y))
        d.text((x, y + th + 4), e['page'], font=f, fill=(200, 200, 205))
    sh.save(out)
    print('contact sheet', out, sh.size)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--tags-only', action='store_true')
    ap.add_argument('--only')
    ap.add_argument('--sheet')
    a = ap.parse_args()
    entries = load_table()
    titles = [e['title'].lower() for e in entries]
    if len(set(titles)) != len(titles):
        sys.exit('Duplicate card titles in pages.json')
    only = set(a.only.split(',')) if a.only else None
    ver = build()
    for e in entries:
        if only and e['page'] not in only:
            continue
        if not a.tags_only:
            rel, n = save(render(e), image_stem(e['page']))
            print(f'{rel:55} {n // 1024:4} KB  {e["title"]}')
        if not e['page'].startswith('learn'):
            if write_tags(e, ver):
                print('  tags ->', e['page'])
    if a.sheet:
        sheet(entries, a.sheet)


if __name__ == '__main__':
    main()
