#!/usr/bin/env python3
"""Build demo-testimonials.html (unlisted preview, Owner order 2026-10-07:
"create 4 variations of these testimonials for hmepage section").

Four testimonials-section variations stacked (A card grid, B marquee wall,
C bento spotlight, D carousel + true stats). Every review on the page is read
at run time from assets/testimonials-data.json by assets/demo-testimonials.js;
nothing is typed into the HTML. noindex,nofollow; NOT in the nav, sitemap or
tools/og/pages.json. index.html is not touched.

The <head> boilerplate, site nav, footer and shared scripts are copied from
features.html. The section markup lives in tools/demo-testimonials/body.html.
Run from the repo root:  python3 tools/demo-testimonials/gen.py
"""
import html
import json
import os
import re

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
SRC = os.path.join(ROOT, 'features.html')
BODY = os.path.join(os.path.dirname(__file__), 'body.html')
OUT = os.path.join(ROOT, 'demo-testimonials.html')

feat = open(SRC, encoding='utf-8').read()
build = json.load(open(os.path.join(ROOT, 'assets', 'version.json')))['build']

head = feat[:feat.index('</head>')]
head = re.sub(r'<!-- Features hub.*?-->\n', '', head, flags=re.S)
head = re.sub(r'<meta name="description"[^>]*>\n', '', head)
head = re.sub(r'<meta (property|name)="(og|twitter):[^>]*>\n', '', head)
head = re.sub(r'<title>.*?</title>\n', '', head)
head = re.sub(r'<link rel="canonical"[^>]*>\n', '', head)
head = re.sub(r'<script type="application/ld\+json">.*?</script>\n?', '', head, flags=re.S)
head = re.sub(r'<link rel="preload" href="assets/images/[^>]*>\n', '', head)
head = head.replace('<link rel="stylesheet" href="assets/features-bento.css?v=%s">' % build,
                    '<link rel="stylesheet" href="assets/demo-testimonials.css?v=%s">' % build)
assert 'demo-testimonials.css' in head, 'features.html stylesheet line changed; update gen.py'
head = head.replace('<meta name="viewport" content="width=device-width, initial-scale=1.0">',
                    '<meta name="viewport" content="width=device-width, initial-scale=1.0">\n'
                    '<!-- DEMO PAGE (Owner order 2026-10-07). Four homepage testimonials variations. Unlisted:\n'
                    '     noindex, not in nav, sitemap or tools/og/pages.json. GENERATED by\n'
                    '     tools/demo-testimonials/gen.py from tools/demo-testimonials/body.html; edit those.\n'
                    '     Reviews come from assets/testimonials-data.json (real member reviews, Owner-confirmed). -->\n'
                    '<meta name="robots" content="noindex,nofollow">')
T = 'Stryker Trading Academy: four testimonials section layouts (demo)'
D = ('Four layout previews for the Stryker homepage testimonials section: card grid, marquee wall, '
     'bento spotlight and carousel, with real member reviews. Education only. Not financial advice.')
img = 'https://strykertrading.com/assets/images/og/demo-testimonials.png?v=%s' % build
alt = 'Stryker demo share card: Testimonials layouts, A B C D, on a black grid with mint accents'
meta = f'''<meta name="description" content="{html.escape(D)}">
<meta property="og:type" content="website">
<meta property="og:site_name" content="Stryker Trading Academy">
<meta property="og:title" content="{html.escape(T)}">
<meta property="og:description" content="{html.escape(D)}">
<meta property="og:url" content="https://strykertrading.com/demo-testimonials">
<meta property="og:image" content="{img}">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:type" content="image/png">
<meta property="og:image:alt" content="{html.escape(alt)}">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{html.escape(T)}">
<meta name="twitter:description" content="{html.escape(D)}">
<meta name="twitter:image" content="{img}">
<meta name="twitter:image:alt" content="{html.escape(alt)}">
<title>Stryker Trading Academy · Testimonials layouts demo</title>
'''
head = head.replace('<meta name="theme-color"', meta + '<meta name="theme-color"')
assert '<title>' in head

nav = feat[feat.index('<nav class="nav" id="site-nav">'):feat.index('</nav>') + 6]
nav = re.sub(r'\s*<div class="fb-progress"[^>]*>.*?</div>', '', nav, flags=re.S)
footer = feat[feat.index('<footer>'):feat.index('</footer>') + 9]
scripts = feat[feat.index('</footer>') + 9:feat.index('</body>')]
scripts = scripts.replace('<script src="assets/features-bento.js?v=%s" defer></script>' % build,
                          '<script src="assets/demo-testimonials.js?v=%s" defer></script>' % build)
scripts = scripts.replace('<script src="assets/dragon-bg.js?v=%s" defer></script>\n' % build, '')
assert 'demo-testimonials.js' in scripts

body = open(BODY, encoding='utf-8').read().replace('@@NAV@@', nav).replace('@@V@@', str(build))

out = (head + '</head>\n<body class="tm-page">\n<a class="skip-link" href="#main">Skip to content</a>\n'
       + body.split('@@MAIN@@')[0] + '<main id="main" tabindex="-1">\n' + body.split('@@MAIN@@')[1]
       + '\n</main>\n' + footer + '\n' + scripts + '</body>\n</html>\n')
open(OUT, 'w', encoding='utf-8').write(out)
print('wrote', os.path.relpath(OUT, ROOT), len(out), 'bytes')
