#!/usr/bin/env python3
"""Build demo-hero.html (unlisted preview, Owner order 2026-10-07:
"show me variations inspired from this for our homnepage hero section").

Four full homepage-hero variations stacked, each with the real site header
above it. noindex,nofollow; NOT in the nav, sitemap or tools/og/pages.json.
index.html is not touched.

Reused rather than retyped: the <head> boilerplate, the site nav, footer and
shared scripts from features.html. The hero markup lives in
tools/demo-hero/body.html (@@NAV@@ = the site nav, @@TICK@@ = ticker items).
Run from the repo root:  python3 tools/demo-hero/gen.py
"""
import html
import json
import os
import re

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
SRC = os.path.join(ROOT, 'features.html')
BODY = os.path.join(os.path.dirname(__file__), 'body.html')
OUT = os.path.join(ROOT, 'demo-hero.html')

feat = open(SRC, encoding='utf-8').read()
build = json.load(open(os.path.join(ROOT, 'assets', 'version.json')))['build']

# ---------------------------------------------------------------- head
head = feat[:feat.index('</head>')]
head = re.sub(r'<!-- Features hub.*?-->\n', '', head, flags=re.S)
head = re.sub(r'<meta name="description"[^>]*>\n', '', head)
head = re.sub(r'<meta (property|name)="(og|twitter):[^>]*>\n', '', head)
head = re.sub(r'<title>.*?</title>\n', '', head)
head = re.sub(r'<link rel="canonical"[^>]*>\n', '', head)
head = re.sub(r'<script type="application/ld\+json">.*?</script>\n?', '', head, flags=re.S)
head = re.sub(r'<link rel="preload" href="assets/images/[^>]*>\n', '', head)
head = head.replace('<link rel="stylesheet" href="assets/features-bento.css?v=%s">' % build,
                    '<link rel="stylesheet" href="assets/demo-hero.css?v=%s">' % build)
assert 'demo-hero.css' in head, 'features.html stylesheet line changed; update gen.py'
head = head.replace('<meta name="viewport" content="width=device-width, initial-scale=1.0">',
                    '<meta name="viewport" content="width=device-width, initial-scale=1.0">\n'
                    '<!-- DEMO PAGE (Owner order 2026-10-07). Four homepage hero variations. Unlisted: noindex,\n'
                    '     not in nav, sitemap or tools/og/pages.json. GENERATED by tools/demo-hero/gen.py from\n'
                    '     tools/demo-hero/body.html; edit those, not this file. -->\n'
                    '<meta name="robots" content="noindex,nofollow">')
T = 'Stryker Trading Academy: four homepage hero variations (demo)'
D = ('Four previews of the Stryker homepage hero: an animated GEX chart card, a full-bleed chart, the dragon emblem and a desk-card stack. '
     '64 chapters, free SPX GEX, 70+ indicators, chapters 1–10 free. Education only. Not financial advice.')
img = 'https://strykertrading.com/assets/images/og/demo-hero.png?v=%s' % build
alt = 'Stryker demo share card: a bold white headline with one phrase in Stryker green over falling candles and a GEX chart card'
meta = f'''<meta name="description" content="{html.escape(D)}">
<meta property="og:type" content="website">
<meta property="og:site_name" content="Stryker Trading Academy">
<meta property="og:title" content="{html.escape(T)}">
<meta property="og:description" content="{html.escape(D)}">
<meta property="og:url" content="https://strykertrading.com/demo-hero">
<meta property="og:image" content="{img}">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:type" content="image/png">
<meta property="og:image:alt" content="{html.escape(alt)}">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{html.escape(T)}">
<meta name="twitter:description" content="{html.escape(D)}">
<meta name="twitter:image" content="{img}">
<meta name="twitter:image:alt" content="{html.escape(alt)}">
<title>Stryker Trading Academy · Hero variations demo</title>
'''
head = head.replace('<meta name="theme-color"', meta + '<meta name="theme-color"')
assert '<title>' in head

# ---------------------------------------------------------------- nav + footer
nav = feat[feat.index('<nav class="nav" id="site-nav">'):feat.index('</nav>') + 6]
nav = re.sub(r'\s*<div class="fb-progress"[^>]*>.*?</div>', '', nav, flags=re.S)
footer = feat[feat.index('<footer>'):feat.index('</footer>') + 9]
scripts = feat[feat.index('</footer>') + 9:feat.index('</body>')]
scripts = scripts.replace('<script src="assets/features-bento.js?v=%s" defer></script>' % build,
                          '<script src="assets/demo-hero.js?v=%s" defer></script>' % build)
scripts = scripts.replace('<script src="assets/dragon-bg.js?v=%s" defer></script>\n' % build, '')
assert 'demo-hero.js' in scripts
if 'market-hours.js' not in scripts:
    scripts = scripts.replace('<script src="assets/demo-hero.js',
                              '<script src="assets/market-hours.js?v=%s"></script>\n<script src="assets/demo-hero.js' % build)

# The first variation keeps the real nav (id, mobile toggle, Features menu); the
# copies above B/C/D are the same markup without the id, marked as copies.
def nav_copy(i):
    if i == 0:
        return nav.replace('<nav class="nav"', '<nav class="nav xh-nav"')
    return nav.replace('<nav class="nav" id="site-nav">', '<nav class="nav xh-nav xh-nav-copy" aria-label="Site header (copy)">')

body = open(BODY, encoding='utf-8').read()
parts = body.split('@@NAV@@')
assert len(parts) == 5, 'body.html needs four @@NAV@@ slots'
body = parts[0] + ''.join(nav_copy(i) + parts[i + 1] for i in range(4))

out = (head + '</head>\n<body class="xh-page">\n<a class="skip-link" href="#main">Skip to content</a>\n'
       '<main id="main" tabindex="-1">\n' + body + '\n</main>\n' + footer + '\n' + scripts + '</body>\n</html>\n')
open(OUT, 'w', encoding='utf-8').write(out)
print('wrote', os.path.relpath(OUT, ROOT), len(out), 'bytes')
