#!/usr/bin/env python3
"""Build demo-home.html (unlisted demo homepage, Owner order 2026-10-06:
"Create a demo home page now consisting of bento grids and hero parallax animations
and images and other crazy stuff ... clean, user friendly and superhooked and CTA").

The page is noindex,nofollow and is NOT in the nav, the sitemap or tools/og/pages.json.
index.html is not touched.

What this script reuses rather than retypes:
  - the <head> boilerplate (device detection, theme snippet, icons) and the site nav and
    footer from features.html, so the header/footer match every other marketing page;
  - chapter numbers, titles and levels from tools/content/chapters-data.js (the same
    source tools/gen-curriculum.js uses for the homepage curriculum block).
The body sections live in tools/demo-home/body.html. Edit those two inputs, then run
from the repo root:  python3 tools/demo-home/gen.py
"""
import html
import json
import os
import re
import subprocess

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
SRC = os.path.join(ROOT, 'features.html')
BODY = os.path.join(os.path.dirname(__file__), 'body.html')
OUT = os.path.join(ROOT, 'demo-home.html')

feat = open(SRC, encoding='utf-8').read()
build = json.load(open(os.path.join(ROOT, 'assets', 'version.json')))['build']

# ---------------------------------------------------------------- head
head = feat[:feat.index('</head>')]
# drop the page-specific bits; keep device detection, theme snippet, icons, shared scripts
head = re.sub(r'<!-- Features hub.*?-->\n', '', head, flags=re.S)
head = re.sub(r'<meta name="description"[^>]*>\n', '', head)
head = re.sub(r'<meta (property|name)="(og|twitter):[^>]*>\n', '', head)
head = re.sub(r'<title>.*?</title>\n', '', head)
head = re.sub(r'<link rel="canonical"[^>]*>\n', '', head)
head = head.replace('<link rel="stylesheet" href="assets/features-bento.css?v=%s">' % build,
                    '<link rel="stylesheet" href="assets/demo-home.css?v=%s">' % build)
head = head.replace('<meta name="viewport" content="width=device-width, initial-scale=1.0">',
                    '<meta name="viewport" content="width=device-width, initial-scale=1.0">\n'
                    '<!-- DEMO HOMEPAGE (Owner order 2026-10-06). Unlisted: noindex, not in nav, sitemap or\n'
                    '     tools/og/pages.json. GENERATED by tools/demo-home/gen.py from tools/demo-home/body.html;\n'
                    '     edit those, not this file. Styles: assets/demo-home.css. Motion: assets/demo-home.js. -->\n'
                    '<meta name="robots" content="noindex,nofollow">')
T = 'Stryker Trading Academy: learn the market like a desk analyst (demo)'
D = ('64 chapters of ICT, SMT and Volume Profile, free SPX GEX levels, charts with 70+ indicators, '
     'a journal and bar-by-bar replay. Chapters 1–10 free. Education only. Not financial advice.')
img = 'https://strykertrading.com/assets/images/og/demo-home.png?v=%s' % build
alt = 'Stryker demo homepage share card: the charts, GEX and curriculum screens floating over a dark chart grid'
meta = f'''<meta name="description" content="{html.escape(D)}">
<meta property="og:type" content="website">
<meta property="og:site_name" content="Stryker Trading Academy">
<meta property="og:title" content="{html.escape(T)}">
<meta property="og:description" content="{html.escape(D)}">
<meta property="og:url" content="https://strykertrading.com/demo-home">
<meta property="og:image" content="{img}">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:type" content="image/png">
<meta property="og:image:alt" content="{html.escape(alt)}">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{html.escape(T)}">
<meta name="twitter:description" content="{html.escape(D)}">
<meta name="twitter:image" content="{img}">
<meta name="twitter:image:alt" content="{html.escape(alt)}">
<title>Stryker Trading Academy · Demo homepage</title>
'''
head = head.replace('<meta name="theme-color"', meta + '<meta name="theme-color"')
head = head.replace('<link rel="preload" href="assets/images/', '<link rel="preload" href="assets/images/')

# ---------------------------------------------------------------- nav + footer
nav = feat[feat.index('<nav class="nav" id="site-nav">'):feat.index('</nav>') + 6]
nav = nav.replace('<div class="fb-progress" aria-hidden="true"><i id="fb-bar"></i></div>',
                  '<div class="dh-progress" aria-hidden="true"><i id="dh-bar"></i></div>')
footer = feat[feat.index('<footer>'):feat.index('</footer>') + 9]
scripts = feat[feat.index('</footer>') + 9:feat.index('</body>')]
scripts = scripts.replace('<script src="assets/features-bento.js?v=%s" defer></script>' % build,
                          '<script src="assets/demo-home.js?v=%s" defer></script>' % build)
scripts = scripts.replace('<script src="assets/dragon-bg.js?v=%s" defer></script>\n' % build, '')

# ---------------------------------------------------------------- chapters rail
js = ("const vm=require('vm'),fs=require('fs');const c={};vm.createContext(c);"
      "vm.runInContext(fs.readFileSync('tools/content/chapters-data.js','utf8')+';this.__C=CHAPTERS_SEED',c);"
      "console.log(JSON.stringify(c.__C.map(x=>({n:x.num,t:x.title,l:x.level}))))")
chapters = json.loads(subprocess.check_output(['node', '-e', js], cwd=ROOT))
LV = {'foundation': ('Foundation', 'lv-f'), 'intermediate': ('Intermediate', 'lv-i'), 'advanced': ('Advanced', 'lv-a')}
cards = []
for i, c in enumerate(chapters):
    name, cls = LV[c['l']]
    free = int(c['n']) <= 10
    href = 'chapter?ch=%s' % c['n'] if free else 'courses'
    cards.append(
        f'<a class="dh-ch {cls}" href="{href}" style="--k:{i}">'
        f'<span class="dh-ch-top"><b class="dh-ch-n">{c["n"]}</b>'
        f'<span class="dh-ch-lv">{name}</span>'
        + ('<span class="dh-ch-free">Free</span>' if free else '<span class="dh-ch-pro">Pro</span>') +
        f'</span><span class="dh-ch-t">{html.escape(c["t"])}</span>'
        f'<span class="dh-ch-bar" aria-hidden="true"><i style="--p:{(i + 1) / len(chapters):.3f}"></i></span></a>')
cards.append('<a class="dh-ch lv-t" href="courses"><span class="dh-ch-top"><b class="dh-ch-n">+12</b>'
             '<span class="dh-ch-lv">Specialist track</span><span class="dh-ch-pro">Pro</span></span>'
             '<span class="dh-ch-t">Volume Profile</span><span class="dh-ch-bar" aria-hidden="true"><i style="--p:1"></i></span></a>')
cards.append('<a class="dh-ch lv-t" href="courses"><span class="dh-ch-top"><b class="dh-ch-n">+10</b>'
             '<span class="dh-ch-lv">Specialist track</span><span class="dh-ch-pro">Pro</span></span>'
             '<span class="dh-ch-t">Prop Firm</span><span class="dh-ch-bar" aria-hidden="true"><i style="--p:1"></i></span></a>')

body = open(BODY, encoding='utf-8').read()
body = body.replace('{{CHAPTERS}}', '\n'.join(cards)).replace('{{V}}', str(build))

out = (head + '</head>\n<body class="dh-page">\n<a class="skip-link" href="#main">Skip to content</a>\n'
       + nav + '\n' + body + '\n' + footer + '\n' + scripts + '</body>\n</html>\n')
open(OUT, 'w', encoding='utf-8').write(out)
print('wrote', os.path.relpath(OUT, ROOT), len(out), 'bytes,', len(chapters), 'chapters')
